version: '2'

services:

  nginx:
    image: jwilder/nginx-proxy:0.6.0
    container_name: northstar-nginx-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    ports:
      - "80:80"
    environment:
      - DEFAULT_HOST=home.solar.system
    networks:
      - dev

  home:
    build:
      context: ./apps/home/.
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: home
    container_name: home
    volumes:
      - ./apps/home:/usr/src/app
    expose:
      - "5000"
    environment:
      - VIRTUAL_HOST=home.solar.system
      - VIRTUAL_PORT=5000
      - http_proxy
      - https_proxy
      - no_proxy
    env_file:
      - ./.env.dev
    networks:
      - dev    

  planets:
    build:
      context: ./services/planets/.
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: planets
    container_name: planets
    volumes:
      - ./services/planets:/api
    env_file:
      - ./.env.dev
    expose:
      - "3000"
    environment:
      - VIRTUAL_HOST=planets.solar.system
      - VIRTUAL_PORT=3000
      - SLS_DEBUG=true
      - http_proxy
      - https_proxy
      - no_proxy
    networks:
      - dev

networks:  
  dev:
    driver: bridge